
package org.example.nycservmobileapp;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.6
 * 2017-12-18T21:50:23.811-05:00
 * Generated source version: 3.0.6
 * 
 */
public final class NYCServMobileApp_NYCServMobileAppSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.example.org/NYCServMobileApp/", "NYCServMobileApp");

    private NYCServMobileApp_NYCServMobileAppSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = NYCServMobileApp_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        NYCServMobileApp_Service ss = new NYCServMobileApp_Service(wsdlURL, SERVICE_NAME);
        NYCServMobileApp port = ss.getNYCServMobileAppSOAP();  
        
        {
        System.out.println("Invoking getViolationInfoForPlate...");
        org.example.nycservmobileapp.GetViolationInfoForPlateRequest _getViolationInfoForPlate_in = null;
        org.example.nycservmobileapp.GetViolationInfoForPlateResult _getViolationInfoForPlate__return = port.getViolationInfoForPlate(_getViolationInfoForPlate_in);
        System.out.println("getViolationInfoForPlate.result=" + _getViolationInfoForPlate__return);


        }
        {
        System.out.println("Invoking createNewHearing...");
        org.example.nycservmobileapp.CreateNewHearingRequest _createNewHearing_in = null;
        org.example.nycservmobileapp.CreateNewHearingResult _createNewHearing__return = port.createNewHearing(_createNewHearing_in);
        System.out.println("createNewHearing.result=" + _createNewHearing__return);


        }
        {
        System.out.println("Invoking getViolationInfo...");
        org.example.nycservmobileapp.GetViolationInfoRequest _getViolationInfo_in = null;
        org.example.nycservmobileapp.GetViolationInfoResult _getViolationInfo__return = port.getViolationInfo(_getViolationInfo_in);
        System.out.println("getViolationInfo.result=" + _getViolationInfo__return);


        }
        {
        System.out.println("Invoking isViolationEligibleForHearing...");
        org.example.nycservmobileapp.IsViolationEligibleForHearingRequest _isViolationEligibleForHearing_in = null;
        org.example.nycservmobileapp.IsViolationEligibleForHearingResult _isViolationEligibleForHearing__return = port.isViolationEligibleForHearing(_isViolationEligibleForHearing_in);
        System.out.println("isViolationEligibleForHearing.result=" + _isViolationEligibleForHearing__return);


        }
        {
        System.out.println("Invoking isViolationInSystem...");
        org.example.nycservmobileapp.IsViolationInSystemRequest _isViolationInSystem_in = null;
        org.example.nycservmobileapp.IsViolationInSystemResult _isViolationInSystem__return = port.isViolationInSystem(_isViolationInSystem_in);
        System.out.println("isViolationInSystem.result=" + _isViolationInSystem__return);


        }

        System.exit(0);
    }

}
