package org.example.nycservmobileapp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.6
 * 2017-12-18T21:50:24.077-05:00
 * Generated source version: 3.0.6
 * 
 */
@WebService(targetNamespace = "http://www.example.org/NYCServMobileApp/", name = "NYCServMobileApp")
@XmlSeeAlso({ObjectFactory.class})
public interface NYCServMobileApp {

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "getViolationInfoForPlate", targetNamespace = "http://www.example.org/NYCServMobileApp/", className = "org.example.nycservmobileapp.GetViolationInfoForPlate")
    @WebMethod(action = "http://www.example.org/NYCServMobileApp/getViolationInfoForPlate")
    @ResponseWrapper(localName = "getViolationInfoForPlateResponse", targetNamespace = "http://www.example.org/NYCServMobileApp/", className = "org.example.nycservmobileapp.GetViolationInfoForPlateResponse")
    public org.example.nycservmobileapp.GetViolationInfoForPlateResult getViolationInfoForPlate(
        @WebParam(name = "in", targetNamespace = "")
        org.example.nycservmobileapp.GetViolationInfoForPlateRequest in
    );

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "createNewHearing", targetNamespace = "http://www.example.org/NYCServMobileApp/", className = "org.example.nycservmobileapp.CreateNewHearing")
    @WebMethod(action = "http://www.example.org/NYCServMobileApp/createNewHearing")
    @ResponseWrapper(localName = "createNewHearingResponse", targetNamespace = "http://www.example.org/NYCServMobileApp/", className = "org.example.nycservmobileapp.CreateNewHearingResponse")
    public org.example.nycservmobileapp.CreateNewHearingResult createNewHearing(
        @WebParam(name = "in", targetNamespace = "")
        org.example.nycservmobileapp.CreateNewHearingRequest in
    );

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "getViolationInfo", targetNamespace = "http://www.example.org/NYCServMobileApp/", className = "org.example.nycservmobileapp.GetViolationInfo")
    @WebMethod(action = "http://www.example.org/NYCServMobileApp/getViolationInfo")
    @ResponseWrapper(localName = "getViolationInfoResponse", targetNamespace = "http://www.example.org/NYCServMobileApp/", className = "org.example.nycservmobileapp.GetViolationInfoResponse")
    public org.example.nycservmobileapp.GetViolationInfoResult getViolationInfo(
        @WebParam(name = "in", targetNamespace = "")
        org.example.nycservmobileapp.GetViolationInfoRequest in
    );

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "isViolationEligibleForHearing", targetNamespace = "http://www.example.org/NYCServMobileApp/", className = "org.example.nycservmobileapp.IsViolationEligibleForHearing")
    @WebMethod(action = "http://www.example.org/NYCServMobileApp/isViolationEligibleForHearing")
    @ResponseWrapper(localName = "isViolationEligibleForHearingResponse", targetNamespace = "http://www.example.org/NYCServMobileApp/", className = "org.example.nycservmobileapp.IsViolationEligibleForHearingResponse")
    public org.example.nycservmobileapp.IsViolationEligibleForHearingResult isViolationEligibleForHearing(
        @WebParam(name = "in", targetNamespace = "")
        org.example.nycservmobileapp.IsViolationEligibleForHearingRequest in
    );

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "isViolationInSystem", targetNamespace = "http://www.example.org/NYCServMobileApp/", className = "org.example.nycservmobileapp.IsViolationInSystem")
    @WebMethod(action = "http://www.example.org/NYCServMobileApp/isViolationInSystem")
    @ResponseWrapper(localName = "isViolationInSystemResponse", targetNamespace = "http://www.example.org/NYCServMobileApp/", className = "org.example.nycservmobileapp.IsViolationInSystemResponse")
    public org.example.nycservmobileapp.IsViolationInSystemResult isViolationInSystem(
        @WebParam(name = "in", targetNamespace = "")
        org.example.nycservmobileapp.IsViolationInSystemRequest in
    );
}
